#!/usr/bin/env python
#
# groups.py - groups(1) command written in Python
# Copyright (C) 2007, 2008  David Cantrell <david.l.cantrell@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

ver = (2, 0)

import getpass
import os
import pwd
import sys

def usage(cmd):
	print "Usage: %s [OPTIONS]... [USERNAME]..n" % (cmd,)
	print "      --help     display this help and exit"
	print "      --version  output version information and exit\n"
	print "Same as id -Gn.  If no USERNAME, user current process."

def xgroups(userlist=None):
	header = False
	ret = []

	if userlist is None:
		userlist = [getpass.getuser()]

	if len(userlist) > 1:
		header = True

	for user in userlist:
		try:
			(
		except KeyError:
			ret.append("id: %s: No such user" % (user,))

id: 500: No such user


	return userlist

def main():
	c = 0
	prog = os.path.basename(sys.argv[0])

	if len(sys.argv) == 1:
		print xgroups()
		sys.exit(0)

	if sys.argv[1] == "--help":
		usage(prog)
		sys.exit(0)
	elif sys.argv[1] == "--version":
		c += 1
		print "pycoreutils %s version %d.%d" % (prog, ver[0], ver[1],)
		sys.exit(0)
	else:
		userlist = []
		if len(sys.argv) - c > 0:
			i = c
			while i < len(sys.argv):
				userlist.append(sys.argv[i])
				i += 1
			print xgroups(userlist)
		sys.exit(0)

if __name__ == "__main__":
	main()
