#!/usr/bin/python -tt
#
# tee - tee(1) command written in Python
# Copyright (C) 2007, 2008, 2009  David Hilley <davidhi@cc.gatech.edu>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

ver = (2, 0)

import getopt
import os
import sys

def usage(cmd):
    print "Usage: %s [OPTION]... [FILE]..." % (cmd,)
    print "Copy standard input to each FILE, and also to standard output.\n"
    print "      -a, --append"
    print "                 append to the given FILEs, do not overwrite"
    print "      -i, --ignore-interrupts"
    print "                 ignore interrupt signals"
    print "      --help     display this help and exit"
    print "      --version  output version information and exit"

def openfile((fname, append)):
    mode = ("wb", "ab")[append]
        
    if fname == "-":
        return sys.stdout
    else:
        f = None
        try:
            f = file(fname, mode, 0)
        except IOError, ioe:
            sys.stderr.write("tee: %s: %s\n" % (fname, ioe.strerror))
        return f

def xtee(files, append=False):
    files = [(f, append) for f in files]

    sys.stdin = os.fdopen(sys.stdin.fileno(), "rb", 0)
    sys.stdout = os.fdopen(sys.stdout.fileno(), "wb", 0)
    
    openfiles = filter(None, map(openfile, files))

    stdin_fd = sys.stdin.fileno()

    while True:
        s = os.read(stdin_fd, 1024)
        if s == "":
            break
        for f in openfiles:
            f.write(s)

    return 0

def main():
    prog = os.path.basename(sys.argv[0])
    append, ignoreint = False, False
    help, version = False, False

    opts, args = [], []

    try:
        opts, args = getopt.getopt(sys.argv[1:], "ai",
                                   ["append", "ignore-interrupts",
                                    "help", "version"])
    except getopt.GetoptError:
        help = True
        
    for o, a in opts:
        if o in ("-a", "--append"):
            append = True
        elif o in ("-i", "--ignore-interrupts"):
            ignoreint = True
        elif o in ("--help"):
            help = True
        elif o in ("--version"):
            version = True

    if help:
        usage(prog)
        sys.exit(0)
    elif version:
        print "pycoreutils %s version %d.%d" % (prog, ver[0], ver[1],)
        sys.exit(0)
    else:
        if ignoreint:
            import signal
            signal.signal(signal.SIGINT, signal.SIG_IGN)

        xtee(args + ['-'], append)
        sys.exit(0)

if __name__ == "__main__":
    main()
