#!/usr/bin/env python
#
# tty.py - tty(1) command written in Python
# Copyright (C) 2007, 2008  David Cantrell <david.l.cantrell@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

pyttyver = (2, 0)

import os
import posix
import sys

def usage(cmd):
	print "Usage: %s [OPTION]..." % (cmd,)
	print "Print the file name of the terminal connected to standard input.\n"
	print "  -s, --silent, --quiet   print nothing, only return an exit status"
	print "      --help     display this help and exit"
	print "      --version  output version information and exit"

def main():
	prog = os.path.basename(sys.argv[0])

	try:
		tty = os.ttyname(sys.stdin.fileno())
	except:
		tty = None

	if len(sys.argv) == 1:
		if tty is None:
			print "not a tty"
		else:
			print tty
		sys.exit(0)

	a = sys.argv[1]

	if a == "--help":
		usage(prog)
		sys.exit(0)
	elif a == "--version":
		print "pycoreutils %s version %d.%d" % (prog, ver[0], ver[1],)
		sys.exit(0)
	elif a == '-s' or a == '--silent' or a == '--quiet':
		sys.exit(posix.isatty(tty))
	else:
		print "%s: extra operand `%s'" % (prog, sys.argv[1],)
		print "Try `%s --help' for more information." % (prog,)
		sys.exit(1)

if __name__ == "__main__":
	main()
