#!/usr/bin/env python -tt
#
# whoami.py - whoami(1) command written in Python
# Copyright (C) 2007, 2008  David Cantrell <david.l.cantrell@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

ver = (2, 0)

import getpass
import os
import sys

def usage(cmd):
	print "Usage: %s [OPTION]..." % (cmd,)
	print "Print the user name associated with the current effective user ID."
	print "Same as id -un.\n"
	print "     --help      display this help and exit"
	print "     --version   output version information and exit"

def main():
	prog = os.path.basename(sys.argv[0])

	if len(sys.argv) == 1:
		print getpass.getuser()
		sys.exit(0)

	if sys.argv[1] == "--help":
		usage(prog)
		sys.exit(0)
	elif sys.argv[1] == "--version":
		print "pycoreutils %s version %d.%d" % (prog, ver[0], ver[1],)
		sys.exit(0)
	else:
		print "%s: extra operand `%s'" % (prog, sys.argv[1],)
		print "Try `%s --help' for more information." % (prog,)
		sys.exit(1)

if __name__ == "__main__":
	main()
